/** @jsx React.DOM */

module.exports = [
 "climacon cloud",
 "climacon cloud sun",
 "climacon cloud moon",
 "climacon rain",
 "climacon rain cloud",
 "climacon rain sun",
 "climacon rain cloud sun",
 "climacon rain moon",
 "climacon rain cloud moon",
 "climacon showers",
 "climacon showers cloud",
 "climacon showers sun",
 "climacon showers cloud sun",
 "climacon showers moon",
 "climacon showers cloud moon",
 "climacon downpour",
 "climacon downpour cloud",
 "climacon downpour sun",
 "climacon downpour cloud sun",
 "climacon downpour moon",
 "climacon downpour cloud moon",
 "climacon drizzle",
 "climacon drizzle cloud",
 "climacon drizzle sun",
 "climacon drizzle cloud sun",
 "climacon drizzle moon",
 "climacon drizzle cloud moon",
 "climacon sleet",
 "climacon sleet cloud",
 "climacon sleet sun",
 "climacon sleet cloud sun",
 "climacon sleet moon",
 "climacon sleet cloud moon",
 "climacon hail",
 "climacon hail cloud",
 "climacon hail sun",
 "climacon hail cloud sun",
 "climacon hail moon",
 "climacon hail cloud moon",
 "climacon flurries",
 "climacon flurries cloud",
 "climacon flurries sun",
 "climacon flurries cloud sun",
 "climacon flurries moon",
 "climacon flurries cloud moon",
 "climacon snow",
 "climacon snow cloud",
 "climacon snow sun",
 "climacon snow cloud sun",
 "climacon snow moon",
 "climacon snow cloud moon",
 "climacon fog",
 "climacon fog cloud",
 "climacon fog sun",
 "climacon fog cloud sun",
 "climacon fog moon",
 "climacon fog cloud moon",
 "climacon haze",
 "climacon haze sun",
 "climacon haze moon",
 "climacon wind",
 "climacon wind cloud",
 "climacon wind sun",
 "climacon wind cloud sun",
 "climacon wind moon",
 "climacon wind cloud moon",
 "climacon lightning",
 "climacon lightning cloud",
 "climacon lightning sun",
 "climacon lightning cloud sun",
 "climacon lightning moon",
 "climacon lightning cloud moon",
 "climacon sun",
 "climacon sun set",
 "climacon sunset",
 "climacon sun rise",
 "climacon sunrise",
 "climacon sun low",
 "climacon sun-low",
 "climacon low-sun",
 "climacon sun lower",
 "climacon sun-lower",
 "climacon lower-sun",
 "climacon moon",
 "climacon moon new",
 "climacon moon waxing crescent",
 "climacon moon first-crescent",
 "climacon moon waxing quarter",
 "climacon moon first-quarter",
 "climacon moon waxing half",
 "climacon moon first-half",
 "climacon moon waxing gibbous",
 "climacon moon first-gibbous",
 "climacon moon waxing three-quarter",
 "climacon moon first-three-quarter",
 "climacon moon full",
 "climacon moon waning gibbous",
 "climacon moon last-gibbous",
 "climacon moon waning three-quarter",
 "climacon moon last-three-quarter",
 "climacon moon waning quarter",
 "climacon moon last-quarter",
 "climacon moon waning half",
 "climacon moon last-half",
 "climacon moon waning crescent",
 "climacon moon last-crescent",
 "climacon snowflake",
 "climacon tornado",
 "climacon thermometer empty",
 "climacon thermometer",
 "climacon thermometer low",
 "climacon thermometer medium-low",
 "climacon thermometer medium-high",
 "climacon thermometer high",
 "climacon thermometer full",
 "climacon celcius",
 "climacon farenheit",
 "climacon compass",
 "climacon compass north",
 "climacon compass east",
 "climacon compass south",
 "climacon compass west",
 "climacon umbrella",
 "climacon sunglasses",
 "climacon cloud cycle",
 "climacon cloud refresh",
 "climacon cloud down",
 "climacon cloud download",
 "climacon cloud up",
 "climacon cloud upload",
];
